mapgroups/urls.py
"""
Experimental URL patterns module.
SRH Jan-2015

For 3rd party modules, I'd like the including project to be able to specify a
namespace for URL names. At the same time, in the module, I'd like to be able
to reverse URLs in views, tests, and models without knowledge of what namespace
the project is using.

The app_name and namespaces are defined external to the module, which seems to
be a design flaw (or maybe I'm interpreting what the design is supposed to do
incorrectly).

The best solution seems to be to provide a 'urls()' function which is called
to get the module's URLs. It sets the app_name to a known value (for use
internally by the module), and namespace to the value provided by the project,
for use in the project's code. (I think app_name should be the name of the
module providing the URLs, but that is not easy to auto-discover, especially if
the URLs are generated).

Short version:
Usage:

    import map_groups.urls
    urls(r'^mount_point/', include(map_groups.urls.urls('Project Name Space'))
"""

from django.conf.urls import url, include
from mapgroups import rpc
from mapgroups.views import MapGroupDetailView, \
    MapGroupCreate, MapGroupListView, JoinMapGroupActionView, \
    RequestJoinMapGroupActionView, MapGroupEditView, MapGroupPreferencesView, \
    LeaveMapGroupActionView, DeleteMapGroupActionView, \
    RemoveMapGroupImageActionView

_urlpatterns = [
    # Map group urls look something like:
    #   midatlanticoceans.org/g/49/swiftly-sinking-sailfish
    # but
    #   midatlanticoceans.org/g/49
    # will also work

    url(r'^$', MapGroupListView.as_view(), name='list'),
    url(r'^create$', MapGroupCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/edit$',
        MapGroupEditView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/edit/remove-image$',
        RemoveMapGroupImageActionView.as_view(), name='remove-image'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$',
        MapGroupDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/preferences$',
        MapGroupPreferencesView.as_view(), name='preferences'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/join$',
        JoinMapGroupActionView.as_view(), name='join'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/leave$',
        LeaveMapGroupActionView.as_view(), name='leave'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/delete$',
        DeleteMapGroupActionView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/join$',
        RequestJoinMapGroupActionView.as_view(), name='request-join'),
]

def urls(namespace='mapgroups'):
    """Returns a 3-tuple for use with include().

    The including module or project can refer to urls as namespace:urlname,
    internally, they are referred to as app_name:urlname.
    """
    return (_urlpatterns, 'mapgroups', namespace)

mapgroups/forms.py
from django import forms

# TODO: Move to common forms module
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from mapgroups.models import MapGroup


class DivForm(object):
    """A form that adds an 'as_div()' method which renders each form element
    inside <div></div> tags.
    """

    def as_div(self):
        "Returns this form rendered as HTML <div>s."
        return self._html_output(
            normal_row='<div%(html_class_attr)s>%(errors)s%(label)s %(field)s%(help_text)s</div>',
            error_row='<div>%s</div>',
            row_ender='</div>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=False)


class BSCheckboxInput(forms.CheckboxInput):
    """A checkbox input with a bootstrap classes that renders as
    <label>[x] name</label>
    """

    TEMPLATE = """{default_input}"""

    def __init__(self, attrs=None, **kwargs):
        attrs = attrs or {}
        attrs.update({'class': 'form-control'})
        super(BSCheckboxInput, self).__init__(attrs, **kwargs)

    def render(self, name, value, attrs=None):
        sup = super(BSCheckboxInput, self)
        default_input = sup.render(name, value, attrs)
        return mark_safe(self.TEMPLATE.format(default_input=default_input))

class CreateGroupForm(forms.Form, DivForm):
    # def __init__(self, *args, **kwargs):
    #     print("Args are", args)
    #     print("Kwargs are", kwargs)
    #     return super(CreateGroupForm, self).__init__()
    name = forms.CharField(max_length=255,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    blurb = forms.CharField(max_length=512,
                            widget=forms.Textarea(attrs={'class': 'form-control'}))
    is_open = forms.BooleanField(required=False, widget=BSCheckboxInput())
    image = forms.ImageField(required=False,
                             widget=forms.FileInput(attrs={'class': 'form-control'}))

    def clean(self):
        print("CreateGroupForm: clean()")

        cleaned_data = super(CreateGroupForm, self).clean()

        return cleaned_data


class EditMapGroupForm(CreateGroupForm):
    """Form for editing group information.
    Currently identical to the Create form.
    """


class RemoveMapGroupImageForm(forms.Form):
    """Form that adds a "Remove image" function to the MapGroup edit form.
    Implemented separately so I don't have to maintain a "Remove" checkbox.
    """
    pass

class JoinMapGroupActionForm(forms.Form, DivForm):
    pass


class LeaveMapGroupActionForm(forms.Form, DivForm):
    pass


class DeleteMapGroupActionForm(forms.Form, DivForm):
    pass


class MapGroupPreferencesForm(forms.Form, DivForm):
    show_real_name = forms.BooleanField(required=False)


class RequestJoinMapGroupActionForm(forms.Form, DivForm):
    message = forms.CharField()

mapgroups/templates/mapgroups/mapgroup_detail.html
{% extends "base.html" %}

{% block page_header %}
    <a class="btn btn-success" href="{% url 'mapgroups:list' %}">&larr; Groups</a>
{% endblock %}


{% block content %}
<style type="text/css">
    .well > img { width: 345px; height: 194px; }
    .well { display: inline-block; background-color: #b1b3b5; }
    li { list-style-type: none; }
</style>

<div class="mapgroup">
    <!-- left column - profile image -->
    <div class="col-md-1">
        <img src="{{ mapgroup.image_url }}" width="124" height="70" style="position: absolute; right: 8px">
    </div>

    <div class="col-md-8">
        <h1 style="margin-top: 0; width: initial; border-left: 1px solid #b1b3b5; margin-left: -12px; padding-left: 12px">{{ mapgroup.name }}</h1>
        <div class="description">
            <p class='rich-text'>{{ mapgroup.blurb }}</p>
        </div>

        <h3>Group Information</h3>
        <p><strong>Group since:</strong> {{ mapgroup.creation_date|date }}</p>
        <p><strong>Owned by:</strong> {% if user_is_member %}
                        {{ owner.user_name_for_group }}
                     {% else %}
                        {{ owner.user.get_short_name }}
                    {% endif %}
        </p>

        <div>
            {# Group action buttons #}

            {% if user_is_member %}
                {% if request.user != mapgroup.owner %}
                    <form method="POST" style="display: inline" action="{% url 'mapgroups:leave' mapgroup.pk mapgroup.slug %}">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">Leave group</button>
                    </form>
                {% endif %}

            {% else %}
                {% if mapgroup.is_open %}
                    {# Anonymous users must use GET, otherwise the request will #}
                    {# be lost in the all the login redirects #}
                    <form method="{% if request.user.is_anonymous %}GET{% else %}POST{% endif %}" style="display: inline" action="{% url 'mapgroups:join' mapgroup.pk mapgroup.slug %}">
                        {% csrf_token %}
                        <p>Welcome! This group is open for anyone to join.</p>
                        <button class="btn btn-success" type="submit">Join Group</button>
                    </form>
                {% else %}
                    <form method="POST" style="display: inline" action="{% url 'mapgroups:request-join' mapgroup.pk mapgroup.slug %}">
                        {% csrf_token %}
                        <p>Request to join this group.</p>
                        <button class="btn btn-success" type="submit">Join Group</button>
                    </form>
                {% endif %}
            {% endif %}

            {% if request.user == mapgroup.owner %}
                <a class="btn btn-success" href="{% url 'mapgroups:edit' mapgroup.pk mapgroup.slug %}">Manage map group</a>
            {% endif %}
        </div>

        {% if user_is_member %}
            <h3>Preferences</h3>

            <form method="POST"
                  action="{% url 'mapgroups:preferences' mapgroup.pk mapgroup.slug %}">
                {% csrf_token %}
                <!--{{ preferences_form.as_div }}-->

                <label>
                {{ preferences_form.show_real_name }} Share my real name with this group.
                </label>

                <script>
                    document.querySelector('#id_show_real_name').onclick = function() {
                        this.form.submit();
                    };
                </script>
            </form>
        {% endif %}

        {% if shared_items %}
            <h3>Shared Items</h3>

            {% if shared_items.bookmarks %}
            <h4>Map Bookmarks</h4>
            <ul>
                {% for object in shared_items.bookmarks %}
                    <li>{{ object.name }}</li> {# Bookmark url is object.url_hash #}
                {% empty %}
                    <li>No shared maps.</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if shared_items.scenarios %}
            <h4>Scenarios</h4>
            <ul>
                {% for object in shared_items.scenarios %}
                    <li>{{ object.name }}</li>
                {% empty %}
                    <li>No shared scenarios.</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if shared_items.leaseblock_selections %}
            <h4>Lease Block Selections</h4>
            <ul>
                {% for object in shared_items.leaseblock_selections %}
                    <li>{{ object.name }}</li>
                {% empty %}
                    <li>No shared lease block selections.</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if shared_items.drawings %}
            <h4>Drawings</h4>
            <ul>
                {% for object in shared_items.drawings %}
                    <li>{{ object.name }}</li>
                {% empty %}
                    <li>No shared drawings.</li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if shared_items.windenergysites %}
            <h4>Wind Energy Sites</h4>
            <ul>
                {% for object in shared_items.windenergysites %}
                    <li>{{ object.name }}</li>
                {% empty %}
                    <li>No shared wind energy sites.</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endif %}
    </div>

    <div class="col-md-3">
        <h3>Group Members</h3>
        <ol>
            {% for member in sorted_member_list %}
            <li>
                <img src="{{ member.user.userdata.profile_image }}" width="32" height="32" />

                {% if membership %}
                    <b>{{ member.user_name_for_group }}</b> <!-- Show real name -->
                {% else %}
                    <b>{{ member.user.get_short_name }}</b> <!-- Show pref name -->
                {% endif %}

                {# call out the current user and owner of the group #}
                {% if request.user == member.user %}
                    (you{% if request.user == mapgroup.owner %}, owner{% endif %})
                {% else %}
                    {% if member.user == mapgroup.owner %}
                        (owner)
                    {% endif %}
                {% endif %}
            </li>
            {% endfor %}
        </ol>
    </div>
</div>

{% endblock %}

mapgroups/templates/mapgroups/mapgroup_edit.html
{% extends "base.html" %}

{% block page_header %}
    <a class="btn btn-success" href="{% url 'mapgroups:detail' mapgroup.pk mapgroup.slug %}">&larr; {{ mapgroup.name }}</a>
{% endblock %}

{% block content %}

            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto;
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i {
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
<div style=" margin: 0 10em 1em 10em; padding: 0 3em">
    <h2 style="text-align: center;">Manage your map group</h2>
    <div>
        <hr />

        <form class="login-form" method="POST" enctype="multipart/form-data" action="{% url 'mapgroups:edit' mapgroup.pk mapgroup.slug %}">
            {% csrf_token %}
            <div class="form-horizontal">
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}" class="col-md-3">{{ form.name.label }}</label>
                        <div class="col-md-9">
                            {{ form.name }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.blurb.id_for_label }}" class="col-md-3" class="form-control">Description</label>
                        <div class="col-md-9">
                            {{ form.blurb }}
                        </div>
                    </div>
                </div>
                <input type="hidden" name="is_open" value="1">
                <!-- <div class="row">
                    <div class="form-group">
                        <div class="col-md-3"><label>Open, or Private?</label></div>
                        <div class="col-md-9">
                            <div class="btn btn-default">
                                <label>
                                    <input id="id_is_open" name="is_open" type="checkbox">
                                    Open Group
                                </label>
                            </div>
                            <p>Tip: Anyone can join an open group. Group owners
                            approve private group membership requests.</p>
                        </div>
                        <label for="{{ form.is_open.id_for_label }}" class="col-md-9"></label>
                    </div>
                </div> -->
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.image.id_for_label }}" class="col-md-3">{{ form.image.label }}</label>
                        <div class="col-md-9">
                            <div class="well">
                                {% if mapgroup.image %}
                                <label for=remove-image-submit class="btn btn-default btn-sm" style="position: absolute; right: 35px">
                                    Remove Image
                                </label>
                                {% endif %}
                                <img src="{{ mapgroup.image_url }}" style="width: 100%">
                            </div>

                            {{ form.image }}<br>
                            Tip: the best image sizes are 345x195 or larger.
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="text-right">
                    <a class="btn btn-inline" href="{% url 'mapgroups:detail' mapgroup.pk mapgroup.slug %}">Cancel changes</a>
                    <label class="btn btn-success">
                        <input style="display: none" type="submit">
                        Save Changes
                    </label>
                </div>
            </div>
        </form>

        <hr>
        <h3>Other options</h3>
        <h4>Delete your group</h4>
        <style>
            blockquote.warn {
                border-left-color: #ea3a54;
                background-color: #eee;
            }
        </style>
        <form method="POST" style="display: inline" action="{% url 'mapgroups:delete' mapgroup.pk mapgroup.slug %}">
            {% csrf_token %}
            {# <button class="btn btn-success" onclick="$('#delete_group').toggle(); return false; ">Delete this group…</button> #}
            <div id="delete_group">
                <blockquote class="warn">
                    <p>Deleting a group is permanent, and cannot be undone.</p>

                    <p class="text-center">
                    <button class="btn btn-danger" type="submit"  onclick='return confirm("Are you sure you want to delete your map group “{{ mapgroup.name }}”?")'>Delete group</button>
                    </p>
                </blockquote>
            </div>
        </form>
    </div>
</div>

<form style="display: none" method="POST" action="{% url 'mapgroups:remove-image' mapgroup.pk mapgroup.slug %}">
    {% csrf_token %}
    <input type="submit" id="remove-image-submit">
</form>

{% endblock %}

mapgroups/templates/mapgroups/mapgroup_form.html
{% extends "base.html" %}

{% block page_header %}
    <a class="btn btn-success" href="{% url 'mapgroups:list'%}">&larr; Groups</a>
{% endblock %}

{% block content %}

            <style>
            .login-form {
                margin-bottom: 1em;
            }
            .login-form > div {
                width: 30em;
                margin: 0 auto;
            }
            .login-form div + div {
                padding-top: 1ex;
            }
            .login-form .form-control {
                color: black;
            }
            .login-form .left-inner-addon { position: relative; }
            .login-form .left-inner-addon input { padding-left: 30px; }
            .login-form .left-inner-addon i {
                position: absolute; padding: 10px 12px; cursor: default;
            }
            </style>
<div style=" margin: 0 10em 1em 10em; padding: 0 3em">
    <h2 style="text-align: center;">Create a map group</h2>
    <div>
        <hr />

        <form class="login-form" method="POST" enctype="multipart/form-data"">
            {% csrf_token %}
            <div class="form-horizontal">
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}" class="col-md-3">{{ form.name.label }}</label>
                        <div class="col-md-9">
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.blurb.id_for_label }}" class="col-md-3" class="form-control">Description</label>
                        <div class="col-md-9">
                            {{ form.blurb }}
                            {{ form.blurb.errors }}
                        </div>
                    </div>
                </div>
                <input type="hidden" name="is_open" value="1">
                <div class="row">
                    <div class="form-group">
                        <label for="{{ form.image.id_for_label }}" class="col-md-3">{{ form.image.label }}</label>
                        <div class="col-md-9">
                            {{ form.image }}<br>
                            {{ form.image.errors }}
                            Tip: the best image sizes are 345x195 or larger.
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="text-right">
                    <label>
                        <button class="btn btn-success" type="submit">Create Group</button>
                    </label>
                </div>
            </div>
        </form>

        <hr>
        <div style="display:none">
        </div>
    </div>
</div>

{% endblock %}

mapgroups/templates/mapgroups/mapgroup_list.html
{% extends "base.html" %}

{% block title %}Join a map group{% endblock %}
{% block page_title %}Join a map group{% endblock %}

{% block content %}
<div class="page-body">
    <style>
        .detail .media-detail .media-inner > a { border-top: none };
    </style>

    <div class="description">
        <p class="rich-text">Groups are an opportunity to share information and
            resources with like-minded ocean users. You can browse groups here and
            request to join groups that are open to the public. Don&rsquo;t see the
            group you are looking for? Create your own group &mdash; anyone can
            start a group.</p>
    </div>

    <a class="btn btn-success btn-lg" href="{% url 'mapgroups:create' %}">To create your own map group, click here.</a><br />
    {% if featured_mapgroups %}
    <h3>Featured Map Groups</h3>
    <div class="grid-view">
        {% for featured in featured_mapgroups %}
            {% include 'mapgroups/mapgroup_list_one.html' with mapgroup=featured.map_group %}
        {% endfor %}
    </div>
    {% endif %}

    <h3>Member Groups</h3>
    <div class="grid-view">
        {% for mg in mapgroups %}
            {% include 'mapgroups/mapgroup_list_one.html' with mapgroup=mg %}
        {% endfor %}
    </div>
</div>

{% endblock %}

mapgroups/templates/mapgroups/mapgroup_list_one.html
<div class="detail">
    <div class="feature">
        <a style="width: 345px; height:194px" href="{% url 'mapgroups:detail' mapgroup.pk mapgroup.slug %}">
            <img src="{{ mapgroup.image_url }}" >
        </a>
    </div>
    <div class="media">
        <div class="media-left media-detail">
            <div class="media-inner">
                <a href="{{ item.url }}" style="padding:0;">
                    <div class="month" title="Date Created">{{ mapgroup.creation_date|date:"m.Y" }}</div>
                    <div class="badge" title="Number of Members">{{ mapgroup.mapgroupmember_set.count }}</div>
                </a>
            </div>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><a href="{% url 'mapgroups:detail' mapgroup.pk mapgroup.slug %}">{{ mapgroup.name }}</a></h4>
            <div class="item-text">{{ mapgroup.blurb }}</div>
        </div>
    </div>
</div>

mapgroups/templates/mapgroups/request_join_group_form.html
{% extends "base.html" %}

{% block content %}

<p>{{ group_name }} requires approval to become a member. Send your request
here.</p>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send request" />
</form>

<p>You will be notified via Email when your request has been approved.</p>

{% endblock %}